---
title: "p8105_hw6_zx2424"
author: "Zhaoqianyu Xiong"
date: "2022-11-26"
output: github_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 2
Import and clean the data.
```{r}
homicide = 
  read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")%>%
  janitor::clean_names() %>%
  mutate(city_state = str_c(city, sep = ",", state)) %>%
  mutate(status = ifelse(disposition == "Closed by arrest", "0", "1")) %>%
  mutate(status = as.integer(status)) %>%
  filter(city_state != "Dallas,TX") %>%
  filter(city_state != "Phoenix,AZ") %>%
  filter(city_state != "Kansas City,MO") %>%
  filter(city_state != "Tulsa,AL") %>%
  filter(victim_race == "White" | victim_race == "Black") %>%
  mutate(victim_age = as.numeric(victim_age))
```

Fit a logistic regression with resolved vs unresolved as the outcome and victim age, sex and race as predictors for Baltimore, MD. And save the output as R object "Baltimore_fit".
```{r}
Baltimore_df = homicide %>%
  filter(city_state == "Baltimore,MD") %>%
  select(status, victim_race, victim_sex, victim_age)

Baltimore_fit = 
  Baltimore_df %>%
  glm(status ~ victim_age + victim_sex + victim_race, data = ., family = binomial())
```

Apply broom::tidy() to this object.
```{r}
broom::tidy(Baltimore_fit)
```

Obtain the estimate keeping all other variables fixed.
```{r}
Baltimore_fit %>%
  broom::tidy() %>%
  select(term, estimate) %>%
  select(term, estimate) %>%
  filter(term == "victim_sexMale")
```

